//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransacoesFinanceiras.Exceptions.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransacoesFinanceiras.Exceptions.Exceptions.ResourceMessagesException", typeof(ResourceMessagesException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OriginalReferenceId é obrigatório para reversões..
        /// </summary>
        public static string ER_001 {
            get {
                return ResourceManager.GetString("ER_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestinationAccountId é obrigatório para transferências..
        /// </summary>
        public static string ER_002 {
            get {
                return ResourceManager.GetString("ER_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountId não pode ser vazio..
        /// </summary>
        public static string ER_003 {
            get {
                return ResourceManager.GetString("ER_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId não pode ser vazio..
        /// </summary>
        public static string ER_004 {
            get {
                return ResourceManager.GetString("ER_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo inicial não pode ser negativo..
        /// </summary>
        public static string ER_005 {
            get {
                return ResourceManager.GetString("ER_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de crédito não pode ser negativo..
        /// </summary>
        public static string ER_006 {
            get {
                return ResourceManager.GetString("ER_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do crédito deve ser maior que zero..
        /// </summary>
        public static string ER_007 {
            get {
                return ResourceManager.GetString("ER_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta não está ativa..
        /// </summary>
        public static string ER_008 {
            get {
                return ResourceManager.GetString("ER_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do débito deve ser maior que zero..
        /// </summary>
        public static string ER_009 {
            get {
                return ResourceManager.GetString("ER_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo disponível insuficiente para débito..
        /// </summary>
        public static string ER_010 {
            get {
                return ResourceManager.GetString("ER_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da reserva deve ser maior que zero..
        /// </summary>
        public static string ER_011 {
            get {
                return ResourceManager.GetString("ER_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo disponível insuficiente para reserva..
        /// </summary>
        public static string ER_012 {
            get {
                return ResourceManager.GetString("ER_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da captura deve ser maior que zero..
        /// </summary>
        public static string ER_013 {
            get {
                return ResourceManager.GetString("ER_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo reservado insuficiente para captura..
        /// </summary>
        public static string ER_014 {
            get {
                return ResourceManager.GetString("ER_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo insuficiente para reverter crédito..
        /// </summary>
        public static string ER_015 {
            get {
                return ResourceManager.GetString("ER_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da transferência deve ser maior que zero..
        /// </summary>
        public static string ER_016 {
            get {
                return ResourceManager.GetString("ER_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambas as contas devem estar ativas..
        /// </summary>
        public static string ER_017 {
            get {
                return ResourceManager.GetString("ER_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo disponível insuficiente para transferência..
        /// </summary>
        public static string ER_018 {
            get {
                return ResourceManager.GetString("ER_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome não pode ser vazio..
        /// </summary>
        public static string ER_019 {
            get {
                return ResourceManager.GetString("ER_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount deve ser maior que zero..
        /// </summary>
        public static string ER_020 {
            get {
                return ResourceManager.GetString("ER_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionId não pode ser vazio..
        /// </summary>
        public static string ER_021 {
            get {
                return ResourceManager.GetString("ER_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceId não pode ser vazio..
        /// </summary>
        public static string ER_022 {
            get {
                return ResourceManager.GetString("ER_022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string não encontrada..
        /// </summary>
        public static string ER_023 {
            get {
                return ResourceManager.GetString("ER_023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflito de concorrência detectado. Tente novamente..
        /// </summary>
        public static string ER_024 {
            get {
                return ResourceManager.GetString("ER_024", resourceCulture);
            }
        }
    }
}
